import { Connection } from 'typeorm';
import { Factory, Seeder } from 'typeorm-seeding';
import {
    PERMISSION_API_SHOW_ME_PROFILE,
    PERMISSION_BACKOFFICE_SHOW_PRODUCT,
    PERMISSION_BACKOFFICE_DETAIL_PRODUCT,
    PERMISSION_BACKOFFICE_UPDATE_PRODUCT,
    PERMISSION_BACKOFFICE_CREATE_PRODUCT,
    PERMISSION_BACKOFFICE_DELETE_PRODUCT,
    PERMISSION_BACKOFFICE_SHOW_CONTENT,
    PERMISSION_BACKOFFICE_DETAIL_CONTENT,
    PERMISSION_BACKOFFICE_UPDATE_CONTENT,
    PERMISSION_BACKOFFICE_CREATE_CONTENT,
    PERMISSION_BACKOFFICE_DELETE_CONTENT,
    PERMISSION_BACKOFFICE_SHOW_PRODUCT_CATEGORY,
    PERMISSION_BACKOFFICE_DETAIL_PRODUCT_CATEGORY,
    PERMISSION_BACKOFFICE_UPDATE_PRODUCT_CATEGORY,
    PERMISSION_BACKOFFICE_CREATE_PRODUCT_CATEGORY,
    PERMISSION_BACKOFFICE_DELETE_PRODUCT_CATEGORY,
    PERMISSION_BACKOFFICE_SHOW_USER,
    PERMISSION_BACKOFFICE_DETAIL_USER,
    PERMISSION_BACKOFFICE_UPDATE_USER,
    PERMISSION_BACKOFFICE_CREATE_USER,
    PERMISSION_BACKOFFICE_DELETE_USER,
    PERMISSION_BACKOFFICE_SHOW_ROLE,
    PERMISSION_BACKOFFICE_DETAIL_ROLE,
    PERMISSION_BACKOFFICE_UPDATE_ROLE,
    PERMISSION_BACKOFFICE_CREATE_ROLE,
    PERMISSION_BACKOFFICE_DELETE_ROLE,
    PERMISSION_BACKOFFICE_SHOW_CONFIG,
    PERMISSION_BACKOFFICE_DETAIL_CONFIG,
    PERMISSION_BACKOFFICE_UPDATE_CONFIG,
    PERMISSION_BACKOFFICE_CREATE_CONFIG,
    PERMISSION_BACKOFFICE_DELETE_CONFIG,
    PERMISSION_BACKOFFICE_SHOW_PERMISSION,
    PERMISSION_BACKOFFICE_DETAIL_PERMISSION,
    PERMISSION_BACKOFFICE_UPDATE_PERMISSION,
    PERMISSION_BACKOFFICE_SHOW_ROLE_PERMISSION,
    PERMISSION_BACKOFFICE_DETAIL_ROLE_PERMISSION,
    PERMISSION_BACKOFFICE_UPDATE_ROLE_PERMISSION,
    PERMISSION_BACKOFFICE_CREATE_ROLE_PERMISSION,
    PERMISSION_BACKOFFICE_DELETE_ROLE_PERMISSION,
    PERMISSION_BACKOFFICE_SHOW_BASE,
    PERMISSION_BACKOFFICE_DETAIL_BASE,
    PERMISSION_BACKOFFICE_UPDATE_BASE,
    PERMISSION_BACKOFFICE_CREATE_BASE,
    PERMISSION_BACKOFFICE_DELETE_BASE,
    PERMISSION_BACKOFFICE_SHOW_WARNING,
    PERMISSION_BACKOFFICE_DETAIL_WARNING,
    PERMISSION_BACKOFFICE_UPDATE_WARNING,
    PERMISSION_BACKOFFICE_CREATE_WARNING,
    PERMISSION_BACKOFFICE_DELETE_WARNING,
    PERMISSION_BACKOFFICE_DETAIL_DEPOSIT_TRASH,
    PERMISSION_BACKOFFICE_SHOW_DEPOSIT_TRASH,
    PERMISSION_BACKOFFICE_VALIDATE_DEPOSIT_TRASH_ITEM,
    PERMISSION_BACKOFFICE_SHOW_DEPOSIT_TRASH_ITEM,
    PERMISSION_BACKOFFICE_UPDATE_DEPOSIT_TRASH,
    PERMISSION_API_SHOW_NOTIFICATION,
    PERMISSION_API_UPDATE_NOTIFICATION,
} from '../../interface-models/iam/permission.interface';
import { Permission } from '../../entities/iam/permission.entity';
import { Exception } from 'handlebars';

export class CreatePermissionSeeder implements Seeder {
    public async run(factory: Factory, connection: Connection): Promise<void> {
        const datax = await connection.getRepository(Permission).find();
        if (datax.length <= 0) {
            const permissionConstant = [
                PERMISSION_API_SHOW_ME_PROFILE,
                PERMISSION_BACKOFFICE_SHOW_PRODUCT,
                PERMISSION_BACKOFFICE_DETAIL_PRODUCT,
                PERMISSION_BACKOFFICE_UPDATE_PRODUCT,
                PERMISSION_BACKOFFICE_CREATE_PRODUCT,
                PERMISSION_BACKOFFICE_DELETE_PRODUCT,

                PERMISSION_BACKOFFICE_SHOW_CONTENT,
                PERMISSION_BACKOFFICE_DETAIL_CONTENT,
                PERMISSION_BACKOFFICE_UPDATE_CONTENT,
                PERMISSION_BACKOFFICE_CREATE_CONTENT,
                PERMISSION_BACKOFFICE_DELETE_CONTENT,

                PERMISSION_BACKOFFICE_SHOW_CONFIG,
                PERMISSION_BACKOFFICE_DETAIL_CONFIG,
                PERMISSION_BACKOFFICE_UPDATE_CONFIG,
                PERMISSION_BACKOFFICE_CREATE_CONFIG,
                PERMISSION_BACKOFFICE_DELETE_CONFIG,

                PERMISSION_BACKOFFICE_SHOW_PRODUCT_CATEGORY,
                PERMISSION_BACKOFFICE_DETAIL_PRODUCT_CATEGORY,
                PERMISSION_BACKOFFICE_UPDATE_PRODUCT_CATEGORY,
                PERMISSION_BACKOFFICE_CREATE_PRODUCT_CATEGORY,
                PERMISSION_BACKOFFICE_DELETE_PRODUCT_CATEGORY,

                PERMISSION_BACKOFFICE_SHOW_USER,
                PERMISSION_BACKOFFICE_DETAIL_USER,
                PERMISSION_BACKOFFICE_UPDATE_USER,
                PERMISSION_BACKOFFICE_CREATE_USER,
                PERMISSION_BACKOFFICE_DELETE_USER,

                PERMISSION_BACKOFFICE_SHOW_ROLE,
                PERMISSION_BACKOFFICE_DETAIL_ROLE,
                PERMISSION_BACKOFFICE_UPDATE_ROLE,
                PERMISSION_BACKOFFICE_CREATE_ROLE,
                PERMISSION_BACKOFFICE_DELETE_ROLE,

                PERMISSION_BACKOFFICE_SHOW_ROLE_PERMISSION,
                PERMISSION_BACKOFFICE_DETAIL_ROLE_PERMISSION,
                PERMISSION_BACKOFFICE_UPDATE_ROLE_PERMISSION,
                PERMISSION_BACKOFFICE_CREATE_ROLE_PERMISSION,
                PERMISSION_BACKOFFICE_DELETE_ROLE_PERMISSION,

                PERMISSION_BACKOFFICE_SHOW_BASE,
                PERMISSION_BACKOFFICE_DETAIL_BASE,
                PERMISSION_BACKOFFICE_UPDATE_BASE,
                PERMISSION_BACKOFFICE_CREATE_BASE,
                PERMISSION_BACKOFFICE_DELETE_BASE,

                PERMISSION_BACKOFFICE_SHOW_WARNING,
                PERMISSION_BACKOFFICE_DETAIL_WARNING,
                PERMISSION_BACKOFFICE_UPDATE_WARNING,
                PERMISSION_BACKOFFICE_CREATE_WARNING,
                PERMISSION_BACKOFFICE_DELETE_WARNING,

                PERMISSION_BACKOFFICE_SHOW_PERMISSION,
                PERMISSION_BACKOFFICE_DETAIL_PERMISSION,
                PERMISSION_BACKOFFICE_UPDATE_PERMISSION,

                PERMISSION_BACKOFFICE_SHOW_DEPOSIT_TRASH,
                PERMISSION_BACKOFFICE_UPDATE_DEPOSIT_TRASH,
                PERMISSION_BACKOFFICE_DETAIL_DEPOSIT_TRASH,

                PERMISSION_BACKOFFICE_VALIDATE_DEPOSIT_TRASH_ITEM,
                PERMISSION_BACKOFFICE_SHOW_DEPOSIT_TRASH_ITEM,

                PERMISSION_API_SHOW_NOTIFICATION,
                PERMISSION_API_UPDATE_NOTIFICATION,
            ];

            const deleteAll = await connection
                .getRepository(Permission)
                .delete({});

            if (!deleteAll) {
                throw new Exception('Error not deleted');
            }

            for (let i = 0; i < permissionConstant.length; i++) {
                const newPermission = connection
                    .getRepository(Permission)
                    .create();
                newPermission.name = permissionConstant[i]
                    .split('-')
                    .join(' ')
                    .toUpperCase();
                newPermission.key = permissionConstant[i];

                try {
                    await connection
                        .getRepository(Permission)
                        .save(newPermission);
                } catch (_) {
                    console.log('pass...');
                }
            }
        }
    }
}
