import { Connection } from 'typeorm';
import { Factory, Seeder } from 'typeorm-seeding';
import {
    PERMISSION_BACKOFFICE_SHOW_PRODUCT,
    PERMISSION_BACKOFFICE_DETAIL_PRODUCT,
    PERMISSION_BACKOFFICE_UPDATE_PRODUCT,
    PERMISSION_BACKOFFICE_CREATE_PRODUCT,
    PERMISSION_BACKOFFICE_DELETE_PRODUCT,
    PERMISSION_BACKOFFICE_SHOW_CONTENT,
    PERMISSION_BACKOFFICE_DETAIL_CONTENT,
    PERMISSION_BACKOFFICE_UPDATE_CONTENT,
    PERMISSION_BACKOFFICE_CREATE_CONTENT,
    PERMISSION_BACKOFFICE_DELETE_CONTENT,
    PERMISSION_BACKOFFICE_SHOW_PRODUCT_CATEGORY,
    PERMISSION_BACKOFFICE_DETAIL_PRODUCT_CATEGORY,
    PERMISSION_BACKOFFICE_UPDATE_PRODUCT_CATEGORY,
    PERMISSION_BACKOFFICE_CREATE_PRODUCT_CATEGORY,
    PERMISSION_BACKOFFICE_DELETE_PRODUCT_CATEGORY,
    PERMISSION_BACKOFFICE_SHOW_USER,
    PERMISSION_BACKOFFICE_DETAIL_USER,
    PERMISSION_BACKOFFICE_UPDATE_USER,
    PERMISSION_BACKOFFICE_CREATE_USER,
    PERMISSION_BACKOFFICE_DELETE_USER,
    PERMISSION_BACKOFFICE_SHOW_ROLE,
    PERMISSION_BACKOFFICE_DETAIL_ROLE,
    PERMISSION_BACKOFFICE_UPDATE_ROLE,
    PERMISSION_BACKOFFICE_CREATE_ROLE,
    PERMISSION_BACKOFFICE_DELETE_ROLE,
    PERMISSION_BACKOFFICE_SHOW_PERMISSION,
    PERMISSION_BACKOFFICE_DETAIL_PERMISSION,
    PERMISSION_BACKOFFICE_UPDATE_PERMISSION,
    PERMISSION_BACKOFFICE_SHOW_ROLE_PERMISSION,
    PERMISSION_BACKOFFICE_DETAIL_ROLE_PERMISSION,
    PERMISSION_BACKOFFICE_UPDATE_ROLE_PERMISSION,
    PERMISSION_BACKOFFICE_CREATE_ROLE_PERMISSION,
    PERMISSION_BACKOFFICE_DELETE_ROLE_PERMISSION,
    PERMISSION_BACKOFFICE_SHOW_CONFIG,
    PERMISSION_BACKOFFICE_DETAIL_CONFIG,
    PERMISSION_BACKOFFICE_UPDATE_CONFIG,
    PERMISSION_BACKOFFICE_CREATE_CONFIG,
    PERMISSION_BACKOFFICE_DELETE_CONFIG,
    PERMISSION_BACKOFFICE_SHOW_BASE,
    PERMISSION_BACKOFFICE_DETAIL_BASE,
    PERMISSION_BACKOFFICE_UPDATE_BASE,
    PERMISSION_BACKOFFICE_CREATE_BASE,
    PERMISSION_BACKOFFICE_DELETE_BASE,
    PERMISSION_BACKOFFICE_SHOW_WARNING,
    PERMISSION_BACKOFFICE_DETAIL_WARNING,
    PERMISSION_BACKOFFICE_UPDATE_WARNING,
    PERMISSION_BACKOFFICE_CREATE_WARNING,
    PERMISSION_BACKOFFICE_DELETE_WARNING,
    PERMISSION_BACKOFFICE_SHOW_DEPOSIT_TRASH,
    PERMISSION_BACKOFFICE_DETAIL_DEPOSIT_TRASH,
    PERMISSION_BACKOFFICE_UPDATE_DEPOSIT_TRASH,
    PERMISSION_BACKOFFICE_VALIDATE_DEPOSIT_TRASH_ITEM,
    PERMISSION_BACKOFFICE_SHOW_DEPOSIT_TRASH_ITEM,
} from '../../interface-models/iam/permission.interface';
import { RolePermission } from '../../entities/iam/role-permission.entity';
import { Role } from 'entities/iam/role.entity';
import { Permission } from 'entities/iam/permission.entity';
import { Exception } from 'handlebars/runtime';

export class CreateRoleAdminPermissionSeeder implements Seeder {
    public async run(factory: Factory, connection: Connection): Promise<void> {
        const permissionConstant = [
            PERMISSION_BACKOFFICE_SHOW_PRODUCT,
            PERMISSION_BACKOFFICE_DETAIL_PRODUCT,
            PERMISSION_BACKOFFICE_UPDATE_PRODUCT,
            PERMISSION_BACKOFFICE_CREATE_PRODUCT,
            PERMISSION_BACKOFFICE_DELETE_PRODUCT,

            PERMISSION_BACKOFFICE_SHOW_CONFIG,
            PERMISSION_BACKOFFICE_DETAIL_CONFIG,
            PERMISSION_BACKOFFICE_UPDATE_CONFIG,
            PERMISSION_BACKOFFICE_CREATE_CONFIG,
            PERMISSION_BACKOFFICE_DELETE_CONFIG,

            PERMISSION_BACKOFFICE_SHOW_DEPOSIT_TRASH,
            PERMISSION_BACKOFFICE_DETAIL_DEPOSIT_TRASH,
            PERMISSION_BACKOFFICE_UPDATE_DEPOSIT_TRASH,

            PERMISSION_BACKOFFICE_SHOW_BASE,
            PERMISSION_BACKOFFICE_DETAIL_BASE,
            PERMISSION_BACKOFFICE_UPDATE_BASE,
            PERMISSION_BACKOFFICE_CREATE_BASE,
            PERMISSION_BACKOFFICE_DELETE_BASE,

            PERMISSION_BACKOFFICE_SHOW_PRODUCT_CATEGORY,
            PERMISSION_BACKOFFICE_DETAIL_PRODUCT_CATEGORY,
            PERMISSION_BACKOFFICE_UPDATE_PRODUCT_CATEGORY,
            PERMISSION_BACKOFFICE_CREATE_PRODUCT_CATEGORY,
            PERMISSION_BACKOFFICE_DELETE_PRODUCT_CATEGORY,

            PERMISSION_BACKOFFICE_SHOW_USER,
            PERMISSION_BACKOFFICE_DETAIL_USER,
            PERMISSION_BACKOFFICE_UPDATE_USER,
            PERMISSION_BACKOFFICE_CREATE_USER,
            PERMISSION_BACKOFFICE_DELETE_USER,

            PERMISSION_BACKOFFICE_SHOW_ROLE,
            PERMISSION_BACKOFFICE_DETAIL_ROLE,
            PERMISSION_BACKOFFICE_UPDATE_ROLE,
            PERMISSION_BACKOFFICE_CREATE_ROLE,
            PERMISSION_BACKOFFICE_DELETE_ROLE,

            PERMISSION_BACKOFFICE_SHOW_WARNING,
            PERMISSION_BACKOFFICE_DETAIL_WARNING,
            PERMISSION_BACKOFFICE_UPDATE_WARNING,
            PERMISSION_BACKOFFICE_CREATE_WARNING,
            PERMISSION_BACKOFFICE_DELETE_WARNING,

            PERMISSION_BACKOFFICE_SHOW_CONTENT,
            PERMISSION_BACKOFFICE_DETAIL_CONTENT,
            PERMISSION_BACKOFFICE_UPDATE_CONTENT,
            PERMISSION_BACKOFFICE_CREATE_CONTENT,
            PERMISSION_BACKOFFICE_DELETE_CONTENT,

            PERMISSION_BACKOFFICE_SHOW_ROLE_PERMISSION,
            PERMISSION_BACKOFFICE_DETAIL_ROLE_PERMISSION,
            PERMISSION_BACKOFFICE_UPDATE_ROLE_PERMISSION,
            PERMISSION_BACKOFFICE_CREATE_ROLE_PERMISSION,
            PERMISSION_BACKOFFICE_DELETE_ROLE_PERMISSION,

            PERMISSION_BACKOFFICE_SHOW_PERMISSION,
            PERMISSION_BACKOFFICE_DETAIL_PERMISSION,
            PERMISSION_BACKOFFICE_VALIDATE_DEPOSIT_TRASH_ITEM,
            PERMISSION_BACKOFFICE_SHOW_DEPOSIT_TRASH_ITEM,
            PERMISSION_BACKOFFICE_UPDATE_PERMISSION,
        ];

        const role = await connection
            .createQueryBuilder(Role, 'roles')
            .where({
                key: 'admin',
            })
            .getOne();

        if (!role) {
            return;
        }

        const deleteAll = await connection
            .getRepository(RolePermission)
            .delete({
                role: {
                    id: role.id,
                },
            });

        if (!deleteAll) {
            throw new Exception('Error not deleted');
        }

        const permissions = await connection
            .createQueryBuilder(Permission, 'permissions')
            .where('permissions.key IN (:...keys)', {
                keys: permissionConstant,
            })
            .getMany();

        for (let i = 0; i < permissions.length; i++) {
            const newRolePermission = connection
                .getRepository(RolePermission)
                .create();
            newRolePermission.role = role;
            newRolePermission.permission = permissions[i];

            try {
                await connection
                    .getRepository(RolePermission)
                    .save(newRolePermission);
            } catch (_) {
                console.log('pass...');
            }
        }
    }
}
